apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-test-demo-shenmiu
  name: prometheus-test-demo-shenmiu
  namespace: cn202009
spec:
  endpoints:
    - interval: 30s
      port: tcp
      path: /actuator/prometheus
      scheme: 'http'
  selector:
    matchLabels:
      app: prometheus-test-demo-shenmiu
  namespaceSelector:
    matchNames:
      - cn202009